### ISSUE TITLE
Error compiling kubel-20200312.135/kubel.el on emacs 27.09, windows

### ISSUE THREAD

**Issue by gravenimage** [abrochard/kubel#10]
Running emacs 27.09 (GNU Emacs 27.0.90 (build 1, x86_64-w64-mingw32) of 2020-03-01).  My init.el just contains package setup for melpa and melpa stable.  Running M-x package-install kubel,  I get the error:

kubel-evil.el:56:1:Error: Wrong type argument: stringp, :init-value

**Comment by abrochard** [comment]
Thank you for reporting this.
I am having issues reproducing. Can you checkout the latest and try to byte compile directly? Also line 56 on kubel-evil is blank for me...

**Comment by jgracindexcom** [comment]
I have the same problem in Emacs 27.0.90 and the latest from master.  Could it be that the minor mode definition is missing the second argument, DOC string?
```
(define-minor-mode kubel-yaml-editing-mode
  :init-value nil
  :keymap (let ((map (make-sparse-keymap)))
            (define-key map (kbd "C-c C-c") 'kubel-apply)
            map))
```

**Comment by abrochard** [comment]
I thought the error that @gravenimage reported came from kubel-evil.el? 
I am on Emacs 26. I can try to upgrade to see if I hit the same issue.
Should I remove the `:init-value nil` from that minor mode?

**Comment by abrochard** [comment]
I confirm that with Emacs 27, I do see an error while trying to byte compile kubel.el (kubel-evil.el is fine though)

```
kubel.el:408:1:Error: Wrong type argument: stringp, :init-value
```

not sure how to fix. will dig

**Comment by abrochard** [comment]
I have a hunch that https://github.com/abrochard/kubel/commit/7d93206d4f7319d80d0d22732480cc1efe2f7913 did the trick. Let me know if not.
