### ISSUE TITLE
"e" to exec on Pod results in dired window of container root

### ISSUE THREAD

**Issue by nrvale0** [abrochard/kubel#11]
When I select a Pod and hit "e" I get a prompt to select a container from the list of running containers and when I select I then get a dired view of the container filesystem but not a shell in the container.

Thoughts?

I'm trying to figure out how to capture an animated .gif to show...

**Comment by abrochard** [comment]
Thank you for your interest in my package!

This is actually the intended behavior. Using "e" opens up a tramp process to that pod. From there you are free to explore in dired mode, edit stuff, or open up a shell with `M-x eshell` or whichever shell you use in emacs.

There was a pretty cool article recently posted on r/emacs on the topic: https://willschenk.com/articles/2020/tramp_tricks/

**Comment by nrvale0** [comment]
Ah, thanks for the clarification. And thanks for the link.

Super excited about being able to use this package in my daily work. Thanks for your efforts.
