### ISSUE TITLE
Need to invalidate kubernetes version cache with kubel 20230905.2159

### ISSUE THREAD

**Issue by Kyrremann** [abrochard/kubel#115]
Latest kubel version (`20230905.2159`) doesn't work for me. Turns out my cache of kubectl version not surprisingly dosen't work.

To solve this I had to clear my local cache by running:
```
(setq kubel--kubernetes-version-cached nil) # then Ctrl x + Ctrl e
```

When I was running the following command after updating:
```
(kubel-kubernetes-version)
```

I got the following error:
```Debugger entered--Lisp error: (json-readtable-error 67)
  signal(json-readtable-error (67))
  json-read()
  json-read-from-string("Client Version: version.Info{Major:\"1\", Minor:\"27\"...")
  kubel-kubernetes-version()
  eval((kubel-kubernetes-version) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

This issue was mainly to document for other people having this problem. So this can probably ble closed.

**Comment by abrochard** [comment]
Thank you for posting! I just merged #116 also which should make things clearer
