### ISSUE TITLE
"File error" when run kubel from a remote buffer

### ISSUE THREAD

**Issue by 404cn** [abrochard/kubel#120]
Some step may reduce this error:

- Open a remote file via tramp
- M-x kubel under that buffer

Then RET on any resource get:

File error: Wrong stderr *kubel - deployments.apps - message-email:err*
tramp-error: Wrong stderr *kubel - deployments.apps - message-email:err*

**Comment by abrochard** [comment]
Is this closed in favor of #118 ?

**Comment by 404cn** [comment]
> Is this closed in favor of #118 ?

Yes, I find it's duplicate
