### ISSUE TITLE
[Question] How to restart deployments or scale them?

### ISSUE THREAD

**Issue by CsBigDataHub** [abrochard/kubel#128]
How do I `restart` deployments? and `scale` Deployments or DaemonSet or StatefulSet without editing the YAML configuration? Like in `k9s`.

**Comment by abrochard** [comment]
HI,
I think you can rollout restart with `j` (it predates k8s native rollout feature so the naming isn't obvious). https://github.com/abrochard/kubel?tab=readme-ov-file#shortcuts.

I'm not sure about scale because I've never used it, but it seems to be `S`

**Comment by CsBigDataHub** [comment]
Thank you.
