### ISSUE TITLE
kubel-rollout-popup is not defined

### ISSUE THREAD

**Issue by hmuniz** [abrochard/kubel#13]
https://github.com/abrochard/kubel/blob/8f65b87f3436e4505651b86c66a0a38d9195cd48/kubel.el#L696
The help-popup is not working because of that.

What should be the value of `Arguments` and `Actions` in kubel-rollout-popup's definition?

**Comment by abrochard** [comment]
Thank you for reporting this! I just pushed https://github.com/abrochard/kubel/commit/7749123f64391e6b7ac91e7cf8ce45ef95b07bee which should fix it.
