### ISSUE TITLE
Symbol’s function definition is void: s-starts-with\?

### ISSUE THREAD

**Issue by dpassen** [abrochard/kubel#14]
Installed kubel via use-package:

```elisp
(use-package kubel
  :ensure t
  :pin    melpa
  :defer  t)
```

and when I run `M-x kubel`, I see:
`kubel--populate-list: Symbol’s function definition is void: s-starts-with\?`

**Comment by dpassen** [comment]
Did a clean re-install and no longer see it.

**Comment by abrochard** [comment]
I think [your fix ](https://github.com/abrochard/kubel/pull/12)solved this? Are you still seeing it?

**Comment by dpassen** [comment]
I thought so, too. Should there be a top-level dependency on s.el? I see I have `20180406.808` installed.

**Comment by abrochard** [comment]
I removed that dependency, let me know if that was it https://github.com/abrochard/kubel/commit/3b1391c94db6ef63dcafdcb210c66df8e0e8cc80
