### ISSUE TITLE
macro expansion failure

### ISSUE THREAD

**Issue by rphillips** [abrochard/kubel#15]
Emacs 27 running Doom Emacs, and I am getting the following failure after running :kubel.

version 20200313.1552

```
Eager macro-expansion failure: (wrong-type-argument stringp :init-value) [2 times]
easy-mmode--mode-docstring: Wrong type argument: stringp, :init-value
```

**Comment by abrochard** [comment]
Could it be the same problem as https://github.com/abrochard/kubel/issues/10 ?

**Comment by rphillips** [comment]
Yep! Thanks!
