### ISSUE TITLE
A way to specify a config file living somewhere other than ~/.kube?

### ISSUE THREAD

**Issue by nrvale0** [abrochard/kubel#2]
See subject.

Looking at the code I don't see a facility for setting envar KUBECONFIG/--kubeconfig parameter to kubectl.

If does not exist then I may attempt a PR.

Thx

**Comment by abrochard** [comment]
Thank you for your interest! There is indeed no current support for that
use case. What kind of config values would you set that way?
And feel free to attempt a PR, I'll try to help the best I can.

**Comment by nrvale0** [comment]
Thanks for the confirmation. Will look into a PR though I've not done a ton of elisp.

For context, I/we have a project where we spin Vagrant and k3s-based devtest environments and the control plane node(s) copy the generated k3s.yaml file to the /vagrant directory for use by kubectl. It would be nice to be able to point kubel at those config files instead of merging them into ~/.kube.

**Comment by abrochard** [comment]
I think that makes sense and should be pretty easy to implement.

Just to make sure, you essentially want to be able to run the equivalent of
```
KUBECONFIG=`pwd`/k3s.yaml kubectl get pods
```
or whatever other `kubectl` command?

**Comment by mox601** [comment]
I am also interested in having this possibility. 
At work we have to run this command once before calling any kubectl command: 
`export KUBECONFIG="/Users/.../.kube/[name of k8s cluster]/config"`

**Comment by abrochard** [comment]
I see, so you want exactly what I was proposing above?
```
KUBECONFIG="/Users/.../.kube/[name of k8s cluster]/config kubectl get pods
```
And it seems that switching context/namespace will change that path?

**Comment by mox601** [comment]
Yes, being able to change the `KUBECONFIG` would be great. 
In this gist https://gist.github.com/mox601/de4fe5d252183d3c02080ba9ace99bc5 I listed the directory tree and the command I use before using kubectl.

**Comment by abrochard** [comment]
Ok I am still a little bit unclear on the use case but can take a shot. Would you be able to test a separate branch locally to see if it works for your workflow?

My main idea right now is to add a config option to set your `KUBECONFIG` env variable when running the `kubel--exec` function which is what calls kubectl.

**Comment by mox601** [comment]
Yes, I can test a separate branch. 
I only need to collect some instructions on how to do that, because I never installed packages from filesystem. But that should be easy.

**Comment by abrochard** [comment]
Actually, before I do any work, can you try setting your `KUBECONFIG` value with
```
(setenv "KUBECONFIG" "/Users/.../.kube/[name of k8s cluster]/config")
```
and then running kubel normally?

**Comment by nrvale0** [comment]
FWIW, when I play with the (setenv) code above it does what I would expect. I tested with ~/.kube/config and ~/.kube/config2 each with distinct set of clusters and then enumerated the available cluster names with kubel-set-context.

**Comment by abrochard** [comment]
Nice! So in that case, is there something else you are expecting in terms of feature or support?

**Comment by nrvale0** [comment]
Since setting the env var does seem to work, its probably a matter of just providing a kubel-prefixed interactive function to set it minibuffer prompt. I might make a pass at it as that seems simple enough to be possible even with my meager elisp knowledge.

**Comment by abrochard** [comment]
Sounds good! Feel free to even make a draft PR and I can take a look at it!
Thanks

**Comment by nrvale0** [comment]
So, this is what I have so far...

```
(defun kubel-set-kubectl-config-file (configfile)
  "Set the path to the kubectl config file."
  (interactive "f")
  (let ((configfile (or configfile "~/.kube/config")))
    (if (file-exists-p configfile)
	(setenv "KUBECONFIG" configfile)
      (error "kubectl config file '%s' does not exist!" configfile))))
```

which was working but now is generating the following error message when M-x kubel-set-context:

```
kubel--extract-value: Args out of range: "Error in configuration: ", 24, 30
```

if I M-x toggle-debug-on-error I'm not getting a stack trace (perhaps because this is interactive?). Do you have any suggestions as to how I might catch the out of range error in the debugger?

**Comment by nrvale0** [comment]
Actually, I think I sorted this out. PR incoming...

**Comment by nrvale0** [comment]
https://github.com/abrochard/kubel/pulls

**Comment by nrvale0** [comment]
https://github.com/abrochard/kubel/pull/19

**Comment by abrochard** [comment]
Amazing. Taking a look now

**Comment by abrochard** [comment]
Looks great! Thank you! I merged it

**Comment by nrvale0** [comment]
Thanks for taking a look. I'm surprisingly pleased to say I have a merged PR in elisp. ;)

**Comment by abrochard** [comment]
You did! And that's how it starts....
