### ISSUE TITLE
Having trouble with kube-evil

### ISSUE THREAD

**Issue by nbrandaleone** [abrochard/kubel#22]
Hello,

I suspect this is more my emacs ignorance than your code. Still, I can not get kubel-evil to work. I have loaded both files (kubel and kugel-evil), however the "hook" is not working. Yes, I do have evil mode and a new version of emacs (26.x). Kubel is working fine on its own, but I can not switch to the evil minor mode.

Any suggestions on how to debug this or recommendations would be appreciated.

Nick (nbrand@mac.com)

**Comment by nbrandaleone** [comment]
I solved the issue.  I simply had to activate the mode (kubel-evil-mode), after loading it. I had assumed that the minor-mode automatically activated itself. My mistake.

Thanks for making such a great library!

Nick

**Comment by abrochard** [comment]
Hi Nick,
Thank you for sharing! I am glad that you like it.
