### ISSUE TITLE
Method 'kubectl' is not known Error

### ISSUE THREAD

**Issue by Syphixs** [abrochard/kubel#28]
I am pretty new to Emacs so this failure could come from another package as well but every time i start a new window with kubel and try to close Emacs or at least the whole session I cannot do that. 
Hope this is related or at least somebody can give me a direction.

![image](https://user-images.githubusercontent.com/33832024/92139163-a813a000-ee0f-11ea-821a-27bae96d1c40.png)

**Comment by abrochard** [comment]
Welcome to Emacs!
This is interesting. You say you see that when you attempt to close Emacs? Which version are you on? Are you using `debug-on-quit`? It looks like it is indeed coming from kubel.

**Comment by Syphixs** [comment]
Hey thanks for your reply!
I am using Doom Emacs v2.0.9 with Emacs 27.1 .
I activated debug on quit but the error stays exactly the same with no further information :/

**Comment by abrochard** [comment]
I see. And without debug-on-quit, what exactly are the symptoms? You see that error message and what else exactly?

**Comment by Syphixs** [comment]
Sorry for my late reply 
I fixed the problem with reinstalling emacs 
Could not trace back any usefull error so reinstalling was by far the fastest solution

**Comment by abrochard** [comment]
No worries! Feel free to re-open if it happens again
