### ISSUE TITLE
cannot list-namespaces when trying to set-namespace

### ISSUE THREAD

**Issue by CsBigDataHub** [abrochard/kubel#38]
Hi @abrochard 

I have seen that you have pushed pull-request https://github.com/abrochard/kubel/pull/29 to master.
Pulled and compiled the latest code to see If I can `list-namespaces` while trying to `set-namespace`.

I am NOT able to do so. I have checked if I can `kubectl auth can-i list namespaces` 

![image](https://user-images.githubusercontent.com/23665525/97883761-e4b62780-1cea-11eb-9cad-33c581f6bb0b.png)

Is there something I am missing?

**Comment by abrochard** [comment]
Thank you for testing it out!
My guess is that this warning in your console is messing up the logic as I'm strictly comparing the output of the command to "yes\n". 

```elisp
(defun kubel--can-get-namespace ()
  "Determine if permissions allow for `kubectl get namespace` in current context."
  (unless kubel--can-get-namespace-cached
    (setq kubel--can-get-namespace-cached
          (equal "yes\n"
                 (shell-command-to-string
                  (format "kubectl --context %s auth can-i list namespaces" kubel-context)))))
  kubel--can-get-namespace-cached)
```
To be sure, you could try manually invoking that function.

Maybe this is relevaent in the kubernetes project: https://github.com/kubernetes/kubernetes/pull/76014
I'm not sure what is the best path forward. It would be good to figure out why that warning is happening and if it is something to take into account.

**Comment by CsBigDataHub** [comment]
@abrochard Thanks for the reply.

Yes that is the issue. can we just use regex matching?

https://emacs.stackexchange.com/a/14861/30647

**Comment by abrochard** [comment]
Yes we can regex match I suppose. I did some digging and that warning actually means that although we can list namespaces, we may not be able to operate inside of them, which makes me think it's ok to ignore in this context.

**Comment by abrochard** [comment]
Actually, this could be more complex than it seems. I just did some test, and `kubectl auth can-i list namespace` does not guarantee that `kubectl get namespace` is allowed.

@CsBigDataHub can you run `kubectl get namespace` in that context and see if it raises any errors?

**Comment by CsBigDataHub** [comment]
@abrochard `kubectl get namespace` did not raise any errors for me.

![image](https://user-images.githubusercontent.com/23665525/98157725-5e8f1200-1e9f-11eb-8e50-cd2b5da2bef9.png)

**Comment by CsBigDataHub** [comment]
Can we do `kubectl auth can-i list namespace -q` and use the exit code?

```
 -q, --quiet=false
     	If true, suppress output and just return the exit code.
```

**Comment by abrochard** [comment]
Ra this is very annoying. The `can-i` command really cannot be trusted. It may say yes but `kubectl get namespace` can fail completely right after.
The options I see are:
1. manual override to ignore the `can-i` command
2. parsing of the `get namespace` output to figure out if an error was raised

**Comment by CsBigDataHub** [comment]
I think if go with option 2 we will need to handle the errors when user tries to select namespace which they do not have access to.

**Comment by abrochard** [comment]
I thought about this over night and I have a tentative solution of the shape of an enum flag: `kubel-use-namespace-list` which can be set to 3 values:
- `auto` is the default and will use the `can-i` command (this is the current state)
- `on` will ignore the `can-i` command and always try to list namespace (that's what you want to set it to in your case)
- `off` will not even try and just do the old behavior before the feature merge

**Comment by CsBigDataHub** [comment]
@abrochard Thanks. That work for me and I think this is reasonable solution to tackle this warning.
