### ISSUE TITLE
Exec into pod failing

### ISSUE THREAD

**Issue by CsBigDataHub** [abrochard/kubel#43]
Error when `kubel-exec-pod` is triggered.

```
files--ensure-directory: Creating directory: Read-only file system, /kubectl:phase1prd
```
Not sure why the command is looking for `root` directory instead of `tramp`.

**Comment by CsBigDataHub** [comment]
@abrochard `exec to eshell` is failing too. while `eshell` exec is successful I cannot run any commands.

I see this in `*Messages*` buffer

```error
Tramp failed to connect.  If this happens repeatedly, try
    ‘M-x tramp-cleanup-this-connection’
```

and this in the split window
![image](https://user-images.githubusercontent.com/23665525/112023031-da14f700-8b00-11eb-9f7e-62dc88b8044d.png)

Essentially I was never able to perform successful `exec` in to a `pod ` from `kubel`

Can we try to use `vterm` to `exec` in to the pod. I found a reddit post about running a command in `vterm` externally.
https://www.reddit.com/r/emacs/comments/ft84xy/run_shell_command_in_new_vterm/

**Comment by abrochard** [comment]
Just to confirm, regardless of which terminal emulator you are using, you cannot `exec` right?
If so, it's probably not because of eshell and vterm won't help. 

I have never seen this problem before so it's very hard to debug. Which version of kubectl are you using? And what about the version of the cluster you are trying to connect to?

**Comment by CsBigDataHub** [comment]
@abrochard I am not able to recreate the issue. I not sure what changed. I think I updated `kubectl` version as well as `kubel` version aswell.

I will close this issue.

**Comment by abrochard** [comment]
Sounds good. Feel free to re-open if it happens again!
