### ISSUE TITLE
Add support for evil keybindings

### ISSUE THREAD

**Issue by dcaixinha** [abrochard/kubel#5]
Hey @abrochard! First of all, kudos on your work on this project and on the presentation on the Emacs meetup – I really enjoyed it!

I've started to use this package but the since I'm using evil mode, a lot of keybindings overlap with evil ones (such as `l` for `logs`). Would it be possible to add support for evil keybindings? I'm just starting to getting my feet weet with Emacs Lisp, but I'd say something similar to [kubernetes-evil.el)[https://github.com/chrisbarrett/kubernetes-el/blob/master/kubernetes-evil.el] would be helpful?

I can try and submit a PR for this, but would appreciate your guidance and pointers. Thanks :pray:

**Comment by abrochard** [comment]
Hi @dcaixinha, thank you very much! I am glad you like it.

You're actually not the first one to request this, I recently merged a [PR](https://github.com/abrochard/kubel/pull/4) from @snowiow specifically to that effect. He will be doing a PR to melpa to add the package there. 

Maybe what you can do in the meantime is manually load the `kubel-evil.el` file and test it out? Share any feedback you may have with the keybindings? I am not an evil user so I just trust you guys.

**Comment by snowiow** [comment]
PR is now provided: https://github.com/melpa/melpa/pull/6492 Sorry for the delay.

**Comment by abrochard** [comment]
Great! Thank you
