### ISSUE TITLE
[feature request] Option to describe pod

### ISSUE THREAD

**Issue by CsBigDataHub** [abrochard/kubel#52]
Option to describe pod

command - 

`kubectl describe pod kafka --context minikube  --namespace default`

**Comment by bard** [comment]
From the pod resource screen, try `C-u RET` instead of `RET`. That runs `describe` (at least on 20210222.2212).

**Comment by CsBigDataHub** [comment]
Thanks, Yes I see that too. I will @abrochard close this. Maybe he wants to leave it open to update the documentation.
