### ISSUE TITLE
Opening edit/describe/so on in the same buffer as kubel

### ISSUE THREAD

**Issue by Kyrremann** [abrochard/kubel#72]
I was wondering if it's possible to open new windows/files in the same buffer as kubel is running?
I'm new to `kubel`, and it looks like a good tool for my daily use of kubernetes (especially when #57 get's merged), but it's a bit irritating to kill all the new files that are opening, and then C-x 0 to close the new buffer.

Generally just opening `describe` as we open `logs` would be a good enough solution for me. Maybe something I can try to implement my self 🤔

**Comment by abrochard** [comment]
Hi @Kyrremann ,
Thank you for your interest!
I'm a bit confused. What do you mean by new file? Can you describe your workflow?

**Comment by Kyrremann** [comment]
Using "new file" was a bit misleading. When I use C-u RET on a k8s resource , it opens a new buffer where the output of kubectl describe is shown. For my usage, I would never edit that output, so it would be nice if I could exit the buffer with "q", like how you leave a log-buffer.

**Comment by abrochard** [comment]
Ah got it! I see what you mean. Does #36 reflect what you are describing?

**Comment by Kyrremann** [comment]
Haha, yes. How could I not see that. Was looking through the issues earlier today.
Thanks, I'll try out some of the tips there.
