### ISSUE TITLE
`kubel-exec-vterm-pod` not spawning a buffer

### ISSUE THREAD

**Issue by dpassen** [abrochard/kubel#88]
Since upgrading kubel to '20220509.104', `kubel-exec-vterm-pod` fails to spawn a vterm buffer. 

These are the only pertinent messages I see:
```
Tramp: Opening connection vterm for REDACTED@REDACTED-6c78fd87d8-ff5z8 using kubectl...done
Successfully exported EDITOR
```

Happy to supply more information to aid in debugging.

**Comment by TxGVNN** [comment]
> I'm not a vterm user so I kind just trust patches/fixes on that side. I know [this](https://github.com/abrochard/kubel/commit/c45e19a215e8e7df80a61c10ca1fa26dcfd1de35) was merged recently. Could it be related?

I think this commit had created this issue. I just tested, and it can not exec into pod in the vterm.
It just opens a vterm on current host, seems vterm doesn't respect on default directory is TRAMP

I'm not a vterm too, so this is just my guess.
